#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
#
# Tailscale-only provisioning for the AI Advent VPS (Ubuntu 26.04).
# Prerequisite done once via the provider's VNC console:
#   curl -fsSL https://tailscale.com/install.sh | sh && tailscale up
#   mkdir -p /root/.ssh && echo '<pubkey>' >> /root/.ssh/authorized_keys
# After that the server is reachable ONLY over the tailnet (public IPv4 at
# Aeza is broken; we never open public ports).
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="deploy/.env.deploy"

KEY="$HOME/.ssh/ai_advent_ed25519"
PUBKEY="$(cat "$KEY.pub")"
SSH_OPTS=(-i "$KEY" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10)

need_file() { [[ -f "$1" ]] || { warn "нет файла $1"; exit 1; }; }
need_file "$KEY"

# All stages run as root over the tailnet.
rsh()        { ssh "${SSH_OPTS[@]}" "root@${TAILNET_HOST}" "$@"; }
rsh_script() { ssh "${SSH_OPTS[@]}" "root@${TAILNET_HOST}" 'bash -s'; }

TOTAL_STAGES=9

banner "AI Advent · настройка VPS (Tailscale-only, Ubuntu 26.04)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Подключение по Tailscale"
say "Предполагается, что через VNC уже выполнено:"
note "  curl -fsSL https://tailscale.com/install.sh | sh && tailscale up"
note "  и наш публичный ключ добавлен в /root/.ssh/authorized_keys"
say "Адрес возьми из VNC: tailscale ip -4 (или MagicDNS-имя)."
ask TAILNET_HOST "Tailnet-адрес сервера (100.x.y.z или имя):"
write_env TAILNET_HOST "$TAILNET_HOST"
say "Проверяем вход:"
rsh 'echo "OK: $(hostname) · $(. /etc/os-release; echo "$PRETTY_NAME")"'
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Обновление системы и базовые пакеты"
rsh_script <<'REMOTE'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y -o Dpkg::Options::=--force-confold
apt-get install -y git curl ca-certificates ufw fail2ban xz-utils
timedatectl set-timezone Europe/Moscow
echo "OS: $(. /etc/os-release; echo "$PRETTY_NAME")"
echo "TZ: $(timedatectl show -p Timezone --value)"
REMOTE
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Пользователь aiadvent (+ passwordless sudo)"
rsh_script <<REMOTE
set -euo pipefail
id aiadvent >/dev/null 2>&1 || adduser --disabled-password --gecos "" aiadvent
usermod -aG sudo aiadvent
printf 'aiadvent ALL=(ALL) NOPASSWD:ALL\n' > /etc/sudoers.d/aiadvent
chmod 440 /etc/sudoers.d/aiadvent
install -d -m 700 -o aiadvent -g aiadvent /home/aiadvent/.ssh
printf '%s\n' '${PUBKEY}' > /home/aiadvent/.ssh/authorized_keys
chmod 600 /home/aiadvent/.ssh/authorized_keys
chown aiadvent:aiadvent /home/aiadvent/.ssh/authorized_keys
id aiadvent
REMOTE
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Node.js 22 LTS (system-wide)"
rsh_script <<'REMOTE'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

install_node_tarball() {
  local arch ver dir
  arch=$(dpkg --print-architecture)
  case "$arch" in amd64) arch=x64 ;; arm64) arch=arm64 ;; esac
  ver=$(curl -fsSL https://nodejs.org/dist/index.json \
        | grep -o '"version":"v22\.[0-9][0-9.]*"' | head -n1 | cut -d'"' -f4)
  [ -n "$ver" ] || ver=v22.20.0
  dir="node-${ver}-linux-${arch}"
  curl -fsSL "https://nodejs.org/dist/${ver}/${dir}.tar.xz" -o /tmp/node.tar.xz
  tar -xJf /tmp/node.tar.xz -C /usr/local --strip-components=1
  rm -f /tmp/node.tar.xz
}

if ! { curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && apt-get install -y nodejs; } 2>/dev/null; then
  echo "NodeSource недоступен — ставлю официальный tarball"
  install_node_tarball
fi

node -v
npm -v
REMOTE
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Firewall (только tailnet) и fail2ban"
rsh_script <<'REMOTE'
set -euo pipefail
ufw default deny incoming
ufw default allow outgoing
ufw allow in on tailscale0
ufw --force enable
systemctl enable --now fail2ban
ufw status verbose
systemctl is-active fail2ban
REMOTE
say "Публичных портов нет — SSH и приложение доступны только через tailnet."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Каталоги"
rsh_script <<'REMOTE'
set -euo pipefail
install -d -m 755 -o aiadvent -g aiadvent /opt/ai-advent-challenge
install -d -m 700 -o aiadvent -g aiadvent /var/lib/ai-advent
ls -ld /opt/ai-advent-challenge /var/lib/ai-advent
REMOTE
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "SSH-харденинг"
say "Отключаем пароль и root-логин по паролю (ключи остаются)."
rsh_script <<'REMOTE'
set -euo pipefail
printf '%s\n' \
  'PasswordAuthentication no' \
  'KbdInteractiveAuthentication no' \
  'PermitRootLogin prohibit-password' \
  'PubkeyAuthentication yes' > /etc/ssh/sshd_config.d/99-hardening.conf
sshd -t
systemctl restart ssh
systemctl is-active ssh
REMOTE
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Код (публичный репозиторий, HTTPS)"
rsh_script <<'REMOTE'
set -euo pipefail
if [ -d /opt/ai-advent-challenge/.git ]; then
  sudo -u aiadvent -H git -C /opt/ai-advent-challenge fetch --all --prune
  sudo -u aiadvent -H git -C /opt/ai-advent-challenge checkout feature/day18 2>/dev/null || true
  sudo -u aiadvent -H git -C /opt/ai-advent-challenge pull --ff-only || true
else
  sudo -u aiadvent -H git clone https://github.com/Finnko/ai-advent-challenge.git /opt/ai-advent-challenge
  sudo -u aiadvent -H git -C /opt/ai-advent-challenge checkout -b feature/day18
fi
sudo -u aiadvent -H git -C /opt/ai-advent-challenge log --oneline -1
sudo -u aiadvent -H git -C /opt/ai-advent-challenge branch --show-current
REMOTE
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Проверка"
rsh_script <<'REMOTE'
set -euo pipefail
echo "== node =="; node -v; npm -v
echo "== tailscale =="; tailscale ip -4
echo "== ufw =="; ufw status | head -8
echo "== fail2ban =="; systemctl is-active fail2ban
echo "== dirs =="; ls -ld /opt/ai-advent-challenge /var/lib/ai-advent
echo "== repo =="; sudo -u aiadvent -H git -C /opt/ai-advent-challenge log --oneline -1
REMOTE
note "Дальше — деплой приложения (env, npm ci, build, systemd) отдельным шагом."
finish
