/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutDay1RouteImport } from './routes/_layout/day1'
import { Route as LayoutDay2RouteImport } from './routes/_layout/day2'
import { Route as LayoutDay3RouteImport } from './routes/_layout/day3'
import { Route as LayoutDay4RouteImport } from './routes/_layout/day4'
import { Route as LayoutDay5RouteImport } from './routes/_layout/day5'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDay1Route = LayoutDay1RouteImport.update({
  id: '/day1',
  path: '/day1',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDay2Route = LayoutDay2RouteImport.update({
  id: '/day2',
  path: '/day2',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDay3Route = LayoutDay3RouteImport.update({
  id: '/day3',
  path: '/day3',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDay4Route = LayoutDay4RouteImport.update({
  id: '/day4',
  path: '/day4',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDay5Route = LayoutDay5RouteImport.update({
  id: '/day5',
  path: '/day5',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/day1': typeof LayoutDay1Route
  '/day2': typeof LayoutDay2Route
  '/day3': typeof LayoutDay3Route
  '/day4': typeof LayoutDay4Route
  '/day5': typeof LayoutDay5Route
}
export interface FileRoutesByTo {
  '/day1': typeof LayoutDay1Route
  '/day2': typeof LayoutDay2Route
  '/day3': typeof LayoutDay3Route
  '/day4': typeof LayoutDay4Route
  '/day5': typeof LayoutDay5Route
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/day1': typeof LayoutDay1Route
  '/_layout/day2': typeof LayoutDay2Route
  '/_layout/day3': typeof LayoutDay3Route
  '/_layout/day4': typeof LayoutDay4Route
  '/_layout/day5': typeof LayoutDay5Route
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day1' | '/day2' | '/day3' | '/day4' | '/day5'
  fileRoutesByTo: FileRoutesByTo
  to: '/day1' | '/day2' | '/day3' | '/day4' | '/day5' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/day1'
    | '/_layout/day2'
    | '/_layout/day3'
    | '/_layout/day4'
    | '/_layout/day5'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/day1': {
      id: '/_layout/day1'
      path: '/day1'
      fullPath: '/day1'
      preLoaderRoute: typeof LayoutDay1RouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/day2': {
      id: '/_layout/day2'
      path: '/day2'
      fullPath: '/day2'
      preLoaderRoute: typeof LayoutDay2RouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/day3': {
      id: '/_layout/day3'
      path: '/day3'
      fullPath: '/day3'
      preLoaderRoute: typeof LayoutDay3RouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/day4': {
      id: '/_layout/day4'
      path: '/day4'
      fullPath: '/day4'
      preLoaderRoute: typeof LayoutDay4RouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/day5': {
      id: '/_layout/day5'
      path: '/day5'
      fullPath: '/day5'
      preLoaderRoute: typeof LayoutDay5RouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutDay1Route: typeof LayoutDay1Route
  LayoutDay2Route: typeof LayoutDay2Route
  LayoutDay3Route: typeof LayoutDay3Route
  LayoutDay4Route: typeof LayoutDay4Route
  LayoutDay5Route: typeof LayoutDay5Route
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutDay1Route: LayoutDay1Route,
  LayoutDay2Route: LayoutDay2Route,
  LayoutDay3Route: LayoutDay3Route,
  LayoutDay4Route: LayoutDay4Route,
  LayoutDay5Route: LayoutDay5Route,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
