/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutDay1RouteImport } from './routes/_layout/day1'
import { Route as LayoutDay2RouteImport } from './routes/_layout/day2'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDay1Route = LayoutDay1RouteImport.update({
  id: '/day1',
  path: '/day1',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDay2Route = LayoutDay2RouteImport.update({
  id: '/day2',
  path: '/day2',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/day1': typeof LayoutDay1Route
  '/day2': typeof LayoutDay2Route
}
export interface FileRoutesByTo {
  '/day1': typeof LayoutDay1Route
  '/day2': typeof LayoutDay2Route
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/day1': typeof LayoutDay1Route
  '/_layout/day2': typeof LayoutDay2Route
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day1' | '/day2'
  fileRoutesByTo: FileRoutesByTo
  to: '/day1' | '/day2' | '/'
  id: '__root__' | '/_layout' | '/_layout/day1' | '/_layout/day2' | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/day1': {
      id: '/_layout/day1'
      path: '/day1'
      fullPath: '/day1'
      preLoaderRoute: typeof LayoutDay1RouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/day2': {
      id: '/_layout/day2'
      path: '/day2'
      fullPath: '/day2'
      preLoaderRoute: typeof LayoutDay2RouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutDay1Route: typeof LayoutDay1Route
  LayoutDay2Route: typeof LayoutDay2Route
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutDay1Route: LayoutDay1Route,
  LayoutDay2Route: LayoutDay2Route,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
